apiVersion: argoproj.io/v1alpha1 # This is an ArgoCD custom resource
kind: Application # Type: Application (ArgoCD's main resource type)
metadata:
  name: my-app-staging # Name of this ArgoCD application (shows in ArgoCD UI)
  namespace: argocd # ArgoCD itself lives in the 'argocd' namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Ensures proper cleanup when app is deleted
spec:
  project: default # 'default' project (basic setup)
  source:
    repoURL: https://gitlab.com/mouadd9/gitops-infra-repo.git # Your GitOps repository URL
    path: helm-chart/         # Points to chart in same repo    
    targetRevision: HEAD # Which branch/tag to track (HEAD = main branch)    
    helm: # HELM CONFIGURATION: How to use the Helm chart
      valueFiles: # Values files to use (order matters - later files override earlier ones)
        - ../environments/values-staging.yaml # Relative path
  destination:
    server: https://kubernetes.default.svc # Target Kubernetes cluster, This means "same cluster where ArgoCD is running"
    namespace: default # Kubernetes namespace to deploy into
  syncPolicy:
    syncOptions:
      - CreateNamespace=true # Create the target namespace if it doesn't exist
