apiVersion: argoproj.io/v1alpha1 # This is an ArgoCD custom resource
kind: Application # Type: Application (ArgoCD's main resource type)
metadata:
  name: my-app-staging # Name of this ArgoCD application (shows in ArgoCD UI)
  namespace: argocd # ArgoCD itself lives in the 'argocd' namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Ensures proper cleanup when app is deleted
spec:
  project: default # 'default' project (basic setup)
  sources:
    - chart: my-spring-app-chart
      repoURL: registry.gitlab.com/mouadd9/cicd-project
      targetRevision: "0.4.0+5370cfe4" # Pipeline updates this
      helm: # HELM CONFIGURATION: How to use the Helm chart
        valueFiles: # Values files to use (order matters - later files override earlier ones)
          - $values/environments/values-staging.yaml
    - repoURL: https://gitlab.com/mouadd9/gitops-infra-repo.git # Your GitOps repository URL
      targetRevision: HEAD # Which branch/tag to track (HEAD = main branch)
      ref: values
  destination:
    server: https://kubernetes.default.svc # Target Kubernetes cluster, This means "same cluster where ArgoCD is running"
    namespace: default # Kubernetes namespace to deploy into
  syncPolicy:
    syncOptions:
      - CreateNamespace=true # Create the target namespace if it doesn't exist
