# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: my-spring-app-config
# data:
#   # This will set the active Spring profile to 'gke'
#   SPRING_PROFILES_ACTIVE: {{ .Values.config.profile | quote }}
#   # You can add other non-sensitive config here
#   # ANOTHER_CONFIG_KEY: "some_value"