apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-app-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.podAppLabel }} # the deployment selects pods labeled with this label
  template:
    metadata:
      labels:
        app: {{ .Values.podAppLabel }}
    spec:
      containers:
      - name: my-spring-app-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        envFrom:
        - configMapRef:
            name: my-spring-app-config # Injects all key-value pairs from our ConfigMap
          # Simple health check for nginx
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5